### ISSUE TITLE
Should I forward any port for this in my router?

### ISSUE THREAD

**Issue by felipecrs** [allenporter/stream-addons#25]
I'm confused. But if it's needed, I suggest documenting it.

If it's not needed, I suggest we disable the port forwarding by default.

And also, have in mind that `host_network: true` will simply ignore any change on port forwarding anyway.

**Comment by allenporter** [comment]
Perhaps the guidance on [Alex](https://github.com/AlexxIT/webrtc)'s custom component would be helpful. It explains how NAT works, what ports you need to forward, etc and option #2 in https://github.com/AlexxIT/webrtc#webrtc-external-access is likely what folks would need to do.

I would recommend this should belong upstream in the RTSPtoWeb or RTSPtoWebRTC project, and then the add-on can point to it.  Perhaps discussing in https://github.com/deepch/RTSPtoWebRTC/issues/148 would be a good place to start, for example.

**Comment by allenporter** [comment]
Continue discussing upstream, so for now this will continue to use host network. The unnecessary ingress/port mapping were removed.

**Comment by felipecrs** [comment]
Thank you, @allenporter!
