### ISSUE TITLE
Support unifi protect skip certificate validation

### ISSUE THREAD

**Issue by allenporter** [allenporter/stream-addons#32]
Need to add some wiring in order to test out  https://github.com/deepch/RTSPtoWeb/issues/82

**Comment by kerhbal** [comment]
hi @allenporter , thanks for the add-on! Though I'm just wondering which branch home assistant add-on is synced with(in terms of version), as I still see the problem even this fix is merged into main branch(just installed add-on today). Thanks!

**Comment by allenporter** [comment]
Hi, this issue is tracking making it work with the add-on. There isn't a way to enable the upstream fix yet as it requires more configuration options.

**Comment by kerhbal** [comment]
I see. thanks

**Comment by allenporter** [comment]
An attempt to include the upstream fix will be in 1.1.0

**Comment by allenporter** [comment]
I don't have an SSL server with an invalid cert so I can't verify this works yet.

**Comment by olbjan** [comment]
I installed this and am using UniFi Protect. My RTSPS camera entities won't load and I get the following on all picture entities with those cameras.
``Failed to start WebRTC stream: RTSPtoWeb server failure: stream channel codec not ready, possible stream offline: Internal Server Error
``

The addon itself isn't logging any errors.
