### ISSUE TITLE
HA Add-on not using http_port config change

### ISSUE THREAD

**Issue by terryhonn** [allenporter/stream-addons#58]
As requested, Allen -

I'm using the Home Assistant add-on, and need to have the RTSPtoWebRTC server serve http via a different port. I've tried:

```
 streams:
  - name: South Shop
    url: rtsp://192.168.1.109:8554/south-shop-cam
  - name: Demo_H264_AAC
    url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
server:
  - http_port: ':8084'
```
but the logs indicate it's still serving on 8083:

```
[GIN-debug] Listening and serving HTTP on :8083
[GIN-debug] [ERROR] listen tcp :8083: bind: address already in use
2022/03/03 15:30:27 Start HTTP Server error listen tcp :8083: bind: address already in use
```

Am I just not putting the param in configuration correctly? Thanks!

**Comment by allenporter** [comment]
Hi,

What is this yaml file? I have never seen this config file before. Maybe you can elaborate in more details on what you are changing.

My impression is the port can be changed in the UI configuration tab for the add-on.

**Comment by Mincka** [comment]
Hi,

In my case, using the addon, the config file as YAML is the following:
```
log_level: info
debug: false
http_port: 8084
rtsp_port: 5541
insecure_skip_verify: false
```

I needed to change the `http_port` because something else was already using 8083.

When I click on "**Open Web UI**", it does not take in account the updated port and tries to open `http://10.0.0.9:8083/`.
If I change the port in the browser, it works file over 8084. I don't know if this link can be dynamic based on configuration parameter. I am not sure if this is related or not to this issue. If you think it's not, I can create another one.

**Comment by allenporter** [comment]
Yes I don't think it's possible to change the web UI port based on doing port config this way.

You just have to go to the port yourself as a workaround.

**Comment by allenporter** [comment]
But like where do you edit a yaml file? I've only ever seen this configurable I'm the UI

**Comment by terryhonn** [comment]
The non-addon version of RTSPtoWebRTC shows an example config.json file like this:

```
{
  "server": {
    "http_port": ":8083"
  },
  "streams": {
    "demo1": {
      "on_demand" : false
      "url": "rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa"
    },
    "demo2": {
      "on_demand" : true
      "url": "rtsp://admin:admin123@10.128.18.224/mpeg4"
    },
    "demo3": {
      "on_demand" : false
      "url": "rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa"
    }
  }
}
```

With the add-on version, from the Configuration tab, you'll see the hamburger button in the upper-right, and if you click on it, you'll see the 'Edit in YAML' option. Clicking on that shows you the YAML editor.

![image](https://user-images.githubusercontent.com/8404272/156959234-f2fe24b6-4b4c-464a-9cf5-f560eee47091.png)

![image](https://user-images.githubusercontent.com/8404272/156959341-67435472-a64b-4d03-8171-31cea06fab0d.png)


I've tried setting the http_port both as above, and as the non-addin version shows in the example config.json, like this:

```
streams:
  - name: Sonoff
    url: rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0
  - name: Demo_H264_AAC
    url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
server:
  http_port: ':8084'

```

but both of those attempts still results in the addin complaining that 8083 is already bound:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
{
  "server": {
    "http_port": ":8083"
  },
  "streams": {
    "Sonoff": {
      "url": "rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0"
    },
    "Demo_H264_AAC": {
      "url": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
    }
  }
}
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
2022/03/06 20:51:42 Stream Try Connect Demo_H264_AAC
[GIN-debug] Loaded HTML Templates (2): 
	- 
	- index.tmpl
[GIN-debug] GET    /                         --> main.serveHTTP.func1 (3 handlers)
[GIN-debug] POST   /recive                   --> main.HTTPAPIServerStreamWebRTC (3 handlers)
[GIN-debug] GET    /codec/:uuid              --> main.serveHTTP.func2 (3 handlers)
[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
2022/03/06 20:51:42 Stream Try Connect Sonoff
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8083
2022/03/06 20:51:42 Server Start Awaiting Signal
[GIN-debug] [ERROR] listen tcp :8083: bind: address already in use
2022/03/06 20:51:42 Start HTTP Server error listen tcp :8083: bind: address already in use

```

It seems strange to me that it's clearly reading the configuration, as changes made to any of the stream parameters, for example, are read and honored. But the http_port param appears to be hard-coded to 8083, which is bound on this server, and the addon fails to complete loading.

If you need further details or logs, I'm happy to assist in troubleshooting.

**Comment by allenporter** [comment]
Hi, those options are not the same as the config.json file. You can only update the options that are available in the UI.

If you want to add streams, then add them configure them in home assistant.  See the video linked at https://community.home-assistant.io/t/add-on-rtsptoweb-and-rtsptowebrtc/387846 for more background.

**Comment by allenporter** [comment]
(Change the option in the UI and it works fine.)

**Comment by terryhonn** [comment]
Allen, if you have a category for idiot users, go ahead and file this one there.

I somehow mixed up your addon (which works just as you said) with this one:
![image](https://user-images.githubusercontent.com/8404272/156964068-08ae68a8-cad8-4bac-905c-d675e84baa91.png)

I'm sorry for wasting your time. Thanks a ton for your work on this.
