### ISSUE TITLE
RTSPWeb remote access with stun server & ice candidates integration with Home Assistant

### ISSUE THREAD

**Issue by allenporter** [allenporter/stream-addons#62]
Creating an issue to track this since we don't have one already.

In order to make remote access work we need the following:
- Stun server support in RTSPtoWeb by @chriswiggins  [Done] (https://github.com/deepch/RTSPtoWeb/pull/128)
- Stun server configuration options in addon by @chriswiggins  (https://github.com/allenporter/stream-addons/pull/59)
- Stun server configuration options in core (https://github.com/home-assistant/core/pull/72574)
- Stun server support in frontend by @chriswiggins  https://github.com/home-assistant/frontend/pull/12084 -- though still needs a way to make this configurable
- Improve ice candidate support.  Simplest way is to disable trickle ice so ice candidates are present in the SDP offer as discussed in the above frontend PR.  Second option is to  actually pass through ice candidates in the signal channel (more complex, and needs to change home assistant webrtc APIs)

**Comment by allenporter** [comment]
Also see https://github.com/deepch/RTSPtoWeb/issues/138

**Comment by Papadoma** [comment]
@allenporter 
You've closed my reported issue about https access and linked to this issue. 
How is my question related stun server &ice candidates integration with HASS? What is the underlying issue?

**Comment by allenporter** [comment]
This issue describes the gaps to provide streams via home assistant remotely. (Not using the method you)

**Comment by TKpizza** [comment]
Is there any update with this?

**Comment by allenporter** [comment]
Hi, have sent a PR to update core to support stun servers which is good to go. The next steps is for frontend support to read the stun server, and we should be good to go and @chriswiggins is taking the lead on that.

**Comment by dangizzi** [comment]
Hi, any update on this?

**Comment by allenporter** [comment]
@chriswiggins do you want to proceed or want me to take it? since it's been 3 months

**Comment by chriswiggins** [comment]
Sorry @allenporter if you can take it that would be great. I don't have time at the moment 😞

**Comment by EliasReuter** [comment]
Hi
Any updates about the "trickle ice" issue?

**Comment by allenporter** [comment]
I've sent frontend PR: https://github.com/home-assistant/frontend/pull/12084

**Comment by allenporter** [comment]
I believe all the necessary features have been added to Home Assistant, and this can work in `2022.11`.

You need to set the options and add a stun server in RTSPtoWeb and that should be sufficient.

**Comment by allenporter** [comment]
I was testing this the other day and it worked, and I didn't need to add any stun server configuration options in addon. I am not sure if both or needed or just having the home assistant client with the stun server is enough. Something to watch out for as people try this out in dev or next home assistant beta.
