### ISSUE TITLE
Reolink RLC-810A not working

### ISSUE THREAD

**Issue by StephaneAdeso** [allenporter/stream-addons#97]
Hi. 
I am running Home Assistant 2023.5.4, Supervisor 2023.04.1 Operating System 10.1Frontend 20230503.3 - latest.
On a Nas Synology with Docker.

I have 8 Cameras from 3 different brands:
- Reolink RLC-810A
- (Hikvision) Safire SF-IPCV023-3W
- Dahua XS-IPDM011A-3W

All the cameras where working fine before installing and using `RTSPtoWeb - WebRTC`.
Now they all works except the **Reolink**. 
I tried rebooting and reinstaling but i still have this problem.
As soon as i uninstall the addon, everything works fine again.
Is there anything i can do to make the reolink camera working?
Thanks !

**Comment by StephaneAdeso** [comment]
I have been researching and I think it is because this camera maybe uses the H265 codec by default and it cannot be modified

**Comment by allenporter** [comment]
Hi, it sounds like the RTSPtoWeb server does not support your camera? This add-on is just adding the server, so you'll want to report this upstream in the component for the server you installed. I don't have this camera and have not investigated what is or isn't supported there...
