### ISSUE TITLE
WebRTC addon does not cache DNS result

### ISSUE THREAD

**Issue by yg-chen-94** [allenporter/stream-addons#98]
I have a Frigate server running somewhere and connected it to Home assistant. To view it in the browser I installed this addon. After that, however, I found out, in my local DNS server, that Home assistant made almost 20000 DNS queries in 24 hours, all to the domain that my camera uses. Disabling WebRTC addon stops the flooding. Is there something I can set to force WebRTC cache the DNS result?
Thanks!

**Comment by allenporter** [comment]
This component is for the addon and not the server itself. Can you file this against the server?
